Traceback (most recent call last):
  File "C:\anaconda\envs\jbook\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\anaconda\envs\jbook\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\anaconda\envs\jbook\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import modules
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32mC:\Users\VERENA~1\AppData\Local\Temp/ipykernel_11508/825824293.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mimport[0m [0mpandas[0m [1;32mas[0m [0mpd[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mnumpy[0m [1;32mas[0m [0mnp[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mimport[0m [0mplotly[0m[1;33m.[0m[0mexpress[0m [1;32mas[0m [0mpx[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;32mimport[0m [0mplotly[0m[1;33m.[0m[0mgraph_objects[0m [1;32mas[0m [0mgo[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'plotly.express'
ModuleNotFoundError: No module named 'plotly.express'

